# Generated by Django 4.2.27 on 2025-12-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(max_length=20, verbose_name="股票代码"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("buy", "买入"), ("sell", "卖出")],
                        max_length=5,
                        verbose_name="买卖方向",
                    ),
                ),
                ("price", models.FloatField(verbose_name="委托价格")),
                ("volume", models.IntegerField(verbose_name="委托数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待成交"),
                            ("filled", "已成交"),
                            ("canceled", "已撤单"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "order_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="委托时间"),
                ),
            ],
            options={
                "verbose_name": "委托订单",
                "verbose_name_plural": "委托订单",
                "db_table": "trade_order",
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(max_length=20, verbose_name="股票代码"),
                ),
                ("price", models.FloatField(verbose_name="成交均价")),
                ("volume", models.IntegerField(verbose_name="成交数量")),
                ("amount", models.FloatField(verbose_name="成交金额")),
                ("fee", models.FloatField(default=0.0, verbose_name="手续费")),
                (
                    "trade_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="成交时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trade.order",
                        verbose_name="关联订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "成交记录",
                "verbose_name_plural": "成交记录",
                "db_table": "trade_record",
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="策略名称")),
                (
                    "code",
                    models.TextField(help_text="Python代码", verbose_name="策略代码"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                        ],
                        default="stopped",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_return",
                    models.FloatField(default=0.0, verbose_name="总收益率"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "量化策略",
                "verbose_name_plural": "量化策略",
                "db_table": "trade_strategy",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trade.strategy",
                verbose_name="关联策略",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(max_length=20, verbose_name="股票代码"),
                ),
                ("volume", models.IntegerField(default=0, verbose_name="持仓股数")),
                ("avg_price", models.FloatField(default=0.0, verbose_name="持仓均价")),
                (
                    "frozen_volume",
                    models.IntegerField(default=0, verbose_name="冻结股数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户持仓",
                "verbose_name_plural": "用户持仓",
                "db_table": "trade_position",
                "unique_together": {("user", "stock_code")},
            },
        ),
        migrations.CreateModel(
            name="IntradayPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="时间点")),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="瞬时总资产"
                    ),
                ),
                ("total_return_rate", models.FloatField(verbose_name="瞬时累计收益率")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "日内5分钟走势",
                "verbose_name_plural": "日内5分钟走势",
                "db_table": "trade_intraday_performance",
                "indexes": [
                    models.Index(
                        fields=["user", "time"], name="trade_intra_user_id_be9f99_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="当日总资产"
                    ),
                ),
                (
                    "day_profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="当日收益"
                    ),
                ),
                ("day_return_rate", models.FloatField(verbose_name="当日收益率")),
                ("total_return_rate", models.FloatField(verbose_name="累计收益率")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "日收益统计",
                "verbose_name_plural": "日收益统计",
                "db_table": "trade_daily_performance",
                "unique_together": {("user", "date")},
            },
        ),
    ]
