# Generated by Django 4.2.27 on 2025-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="stock_pool",
            field=models.TextField(
                blank=True,
                default="",
                help_text="以英文逗号分隔的股票代码，例如: sh.600000,sz.000001",
                verbose_name="股票池",
            ),
        ),
    ]
