# Generated by Django 4.2.27 on 2025-12-28 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_strategy_stock_pool"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_mock_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="当前模拟时间"
                    ),
                ),
                (
                    "time_speed",
                    models.FloatField(default=1.0, verbose_name="时间流速倍率"),
                ),
                (
                    "skip_non_trading",
                    models.BooleanField(default=False, verbose_name="自动跳过休市"),
                ),
                ("last_update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统上帝设置",
                "verbose_name_plural": "系统上帝设置",
                "db_table": "system_settings",
            },
        ),
    ]
