# Generated by Django 4.2.27 on 2025-12-29 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="委托时间"
            ),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="trade_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="成交时间"
            ),
        ),
    ]
