# Generated by Django 4.2.27 on 2026-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_alter_order_order_time_alter_traderecord_trade_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeFlowSettings",
            fields=[],
            options={
                "verbose_name": "1. 时间流速控制 (安全)",
                "verbose_name_plural": "1. 时间流速控制 (安全)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("trade.systemsettings",),
        ),
        migrations.CreateModel(
            name="TimeResetSettings",
            fields=[],
            options={
                "verbose_name": "2. 时间穿越 & 重置 (危险)",
                "verbose_name_plural": "2. 时间穿越 & 重置 (危险)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("trade.systemsettings",),
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="skip_non_trading",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(verbose_name="委托时间"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="code",
            field=models.TextField(verbose_name="策略代码"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="stock_pool",
            field=models.TextField(
                blank=True, default="", help_text="英文逗号分隔", verbose_name="股票池"
            ),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="trade_time",
            field=models.DateTimeField(verbose_name="成交时间"),
        ),
    ]
