# Generated by Django 4.2.27 on 2025-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png",
                max_length=300,
                verbose_name="头像URL",
            ),
        ),
    ]
