# Generated by Django 4.2.27 on 2025-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png",
                max_length=300,
                null=True,
                verbose_name="头像URL",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="账户余额"
            ),
        ),
    ]
