# Generated by Django 4.2.27 on 2025-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_avatar_alter_userprofile_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="initial_capital",
            field=models.DecimalField(
                decimal_places=2,
                default=200000.0,
                max_digits=14,
                verbose_name="初始本金",
            ),
        ),
    ]
