# Generated by Django 4.2.27 on 2026-02-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_initial_capital"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_market_value",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="总市值"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_total_assets",
            field=models.DecimalField(
                decimal_places=2, default=200000.0, max_digits=14, verbose_name="总资产"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="资产最后更新时间"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="withdrawable_cash",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="可取资金"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="可用余额"
            ),
        ),
    ]
