# Generated by Django 4.2.27 on 2026-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_last_market_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_profit",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="当日收益"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=14, verbose_name="总收益"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
        ),
    ]
