# Generated by Django 4.2.27 on 2026-03-10 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="因子名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="因子代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="因子描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "量化因子",
                "verbose_name_plural": "量化因子",
                "db_table": "backtest_factor",
            },
        ),
        migrations.CreateModel(
            name="BacktestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="回测任务名称"),
                ),
                ("start_date", models.DateField(verbose_name="回测开始日期")),
                ("end_date", models.DateField(verbose_name="回测结束日期")),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000.0,
                        max_digits=15,
                        verbose_name="初始资金",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "factor_weights",
                    models.JSONField(default=dict, verbose_name="因子权重配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测任务",
                "verbose_name_plural": "回测任务",
                "db_table": "backtest_task",
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annualized_return",
                    models.FloatField(blank=True, null=True, verbose_name="年化收益率"),
                ),
                (
                    "max_drawdown",
                    models.FloatField(blank=True, null=True, verbose_name="最大回撤"),
                ),
                (
                    "sharpe_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="夏普比率"),
                ),
                (
                    "win_rate",
                    models.FloatField(blank=True, null=True, verbose_name="胜率"),
                ),
                (
                    "equity_curve",
                    models.JSONField(default=list, verbose_name="资金曲线"),
                ),
                (
                    "positions_history",
                    models.JSONField(default=list, verbose_name="持仓历史"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="backtest.backtesttask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测结果",
                "verbose_name_plural": "回测结果",
                "db_table": "backtest_result",
            },
        ),
    ]
