# Generated by Django 4.2.27 on 2025-12-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("date", models.DateField(verbose_name="交易日期")),
                ("open", models.FloatField(verbose_name="开盘价")),
                ("high", models.FloatField(verbose_name="最高价")),
                ("low", models.FloatField(verbose_name="最低价")),
                ("close", models.FloatField(verbose_name="收盘价")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("amount", models.FloatField(verbose_name="成交额")),
            ],
            options={
                "verbose_name": "股票数据",
                "verbose_name_plural": "股票数据",
                "db_table": "stock_data",
                "indexes": [
                    models.Index(
                        fields=["code", "date"], name="stock_data_code_85e748_idx"
                    )
                ],
            },
        ),
    ]
