# Generated by Django 4.2.27 on 2025-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="股票代码"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属行业"
                    ),
                ),
            ],
            options={
                "verbose_name": "股票基本信息",
                "verbose_name_plural": "股票基本信息",
            },
        ),
    ]
