# Generated by Django 4.2.27 on 2025-12-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stockbasicinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockbasicinfo",
            name="industry",
        ),
    ]
