# Generated by Django 4.2.27 on 2025-12-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_remove_stockbasicinfo_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateTimeField(verbose_name="交易时间"),
        ),
    ]
