# Generated by Django 4.2.27 on 2025-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_stockdata_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMinuteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("date", models.DateTimeField(verbose_name="交易时间")),
                ("open", models.FloatField(verbose_name="开盘价")),
                ("high", models.FloatField(verbose_name="最高价")),
                ("low", models.FloatField(verbose_name="最低价")),
                ("close", models.FloatField(verbose_name="收盘价")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                ("amount", models.FloatField(verbose_name="成交额")),
            ],
            options={
                "verbose_name": "分钟数据",
                "verbose_name_plural": "分钟数据",
                "db_table": "stock_data_minute",
            },
        ),
        migrations.AlterModelOptions(
            name="stockdata",
            options={"verbose_name": "日线数据", "verbose_name_plural": "日线数据"},
        ),
        migrations.RenameIndex(
            model_name="stockdata",
            new_name="stock_data__code_0ce8f4_idx",
            old_name="stock_data_code_85e748_idx",
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateField(verbose_name="交易日期"),
        ),
        migrations.AlterModelTable(
            name="stockdata",
            table="stock_data_daily",
        ),
        migrations.AddIndex(
            model_name="stockminutedata",
            index=models.Index(
                fields=["code", "date"], name="stock_data__code_b67321_idx"
            ),
        ),
    ]
