# Generated by Django 4.2.27 on 2026-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_stockminutedata_alter_stockdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIndexBasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="指数代码"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="指数名称")),
                ("market", models.CharField(max_length=10, verbose_name="交易所")),
            ],
            options={
                "verbose_name": "大盘指数基本信息",
                "verbose_name_plural": "大盘指数基本信息",
                "db_table": "market_index_basic",
            },
        ),
        migrations.CreateModel(
            name="MarketIndexDailyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="指数代码")),
                ("date", models.DateField(verbose_name="交易日期")),
                ("open", models.FloatField(verbose_name="开盘点位")),
                ("high", models.FloatField(verbose_name="最高点位")),
                ("low", models.FloatField(verbose_name="最低点位")),
                ("close", models.FloatField(verbose_name="收盘点位")),
                ("volume", models.BigIntegerField(default=0, verbose_name="成交量")),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="成交额"),
                ),
                (
                    "amplitude",
                    models.FloatField(blank=True, null=True, verbose_name="振幅"),
                ),
                (
                    "change_pct",
                    models.FloatField(blank=True, null=True, verbose_name="涨跌幅"),
                ),
                (
                    "change_amount",
                    models.FloatField(blank=True, null=True, verbose_name="涨跌额"),
                ),
                (
                    "turnover_rate",
                    models.FloatField(blank=True, null=True, verbose_name="换手率"),
                ),
                (
                    "source",
                    models.CharField(
                        default="akshare", max_length=20, verbose_name="数据源"
                    ),
                ),
            ],
            options={
                "verbose_name": "大盘指数日线数据",
                "verbose_name_plural": "大盘指数日线数据",
                "db_table": "market_index_daily",
            },
        ),
        migrations.CreateModel(
            name="MarketIndexMinuteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="指数代码")),
                ("date", models.DateTimeField(verbose_name="交易时间")),
                ("open", models.FloatField(verbose_name="开盘点位")),
                ("high", models.FloatField(verbose_name="最高点位")),
                ("low", models.FloatField(verbose_name="最低点位")),
                ("close", models.FloatField(verbose_name="收盘点位")),
                ("volume", models.BigIntegerField(default=0, verbose_name="成交量")),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="成交额"),
                ),
                (
                    "source",
                    models.CharField(
                        default="pytdx", max_length=20, verbose_name="数据源"
                    ),
                ),
            ],
            options={
                "verbose_name": "大盘指数5分钟数据",
                "verbose_name_plural": "大盘指数5分钟数据",
                "db_table": "market_index_minute",
                "indexes": [
                    models.Index(
                        fields=["code", "date"], name="market_inde_code_4213e2_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="marketindexminutedata",
            constraint=models.UniqueConstraint(
                fields=("code", "date"), name="uniq_market_index_minute"
            ),
        ),
        migrations.AddIndex(
            model_name="marketindexdailydata",
            index=models.Index(
                fields=["code", "date"], name="market_inde_code_de9990_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketindexdailydata",
            constraint=models.UniqueConstraint(
                fields=("code", "date"), name="uniq_market_index_daily"
            ),
        ),
    ]
